name: Fetch and publish new match data
on:
  push:
    branches: [ master, ci ]
  workflow_dispatch:
  schedule:
    - cron: "17 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout League-of-Legends
        uses: actions/checkout@v2
        
      - name: Checkout scripts
        uses: actions/checkout@v2
        with:
          repository: ics-tools/scripts
          path: "external-scripts"
        
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.X'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: Convert notebook to script
        run: jupyter nbconvert --to script "Get matches data.ipynb"
      
      - name: Run script
        run: python3 "Get matches data.py"
